version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "9001:9001"
    command: uvicorn app.main:app --host 0.0.0.0 --port 9001
    volumes:
      - .:/parser_a
    restart: always
