version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "9002:9002"
    command: uvicorn app.main:app --host 0.0.0.0 --port 9002
    volumes:
      - .:/parser_a
    restart: always

